server:
  {
  ip:127.0.0.1
  port:8080
  }

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  
quote_key: "quote:daily"

      
   
# spider:
#   [{
#     address:
#     api_format:{}
#     mapper:[
#       {f1:s1,f2:tag,}
#     ]
#     fix:{
#       {"tag":故事}
#     }
#   }]